# Generated by Django 3.2.6 on 2021-08-28 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketCap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_id', models.IntegerField(verbose_name='coin id')),
                ('coin_name', models.CharField(max_length=255, verbose_name='coin name')),
                ('coin_code', models.CharField(max_length=20, verbose_name='coin code')),
                ('info_url', models.CharField(max_length=2083, verbose_name='info url')),
                ('price', models.FloatField(verbose_name='price')),
                ('h1', models.FloatField(verbose_name='h1')),
                ('h24', models.FloatField(verbose_name='h24')),
                ('d7', models.FloatField(verbose_name='d7')),
                ('h24_volume', models.FloatField(verbose_name='h24')),
                ('market_cap', models.FloatField(verbose_name='market')),
                ('sparkline_url', models.CharField(max_length=2083, verbose_name='sparkline url')),
            ],
        ),
        migrations.CreateModel(
            name='MarketCapFormModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_select_coin_id', models.BooleanField()),
                ('coin_id', models.IntegerField()),
                ('is_select_coin_name', models.BooleanField()),
                ('coin_name', models.CharField(max_length=255)),
                ('is_select_coin_code', models.BooleanField()),
                ('coin_code', models.CharField(max_length=20)),
                ('is_select_price', models.BooleanField()),
                ('min_price', models.IntegerField()),
                ('max_price', models.IntegerField()),
                ('is_select_1h', models.BooleanField()),
                ('min_1h', models.IntegerField()),
                ('max_1h', models.IntegerField()),
                ('is_select_24h', models.BooleanField()),
                ('min_24h', models.IntegerField()),
                ('max_24h', models.IntegerField()),
                ('is_select_7d', models.BooleanField()),
                ('min_7d', models.IntegerField()),
                ('max_7d', models.IntegerField()),
                ('is_select_24h_volume', models.BooleanField()),
                ('min_24h_volume', models.IntegerField()),
                ('max_24h_volume', models.IntegerField()),
                ('is_select_market_cap', models.BooleanField()),
                ('min_market_cap', models.IntegerField()),
                ('max_market_cap', models.IntegerField()),
            ],
        ),
    ]
